Feature/xrp fultx
DcentWallet/dcent-web-connector pull request #22
Opened 2020-09-21 07:13 UTC by lix82

2020-09-21 07:45 UTC, KyungeunKim approved these changes

2020-09-21 11:00 UTC, paromix requested changes
Please add unit test cases related with XRP transaction.
The guidance can be gotten from @KyungeunKim

2020-09-22 03:30 UTC, paromix approved these changes

2020-09-22 03:31 UTC, KyungeunKim requested changes

2020-09-22 03:31 UTC, KyungeunKim commented on index.html
> +          "TransactionType": "AccountSet",
https://xrpl.org/transaction-types.html 
여기 보니깐,  transaction type 이 꽤 많던데.. 우리가 지원하는 종류를 먼저 걸러주는게 좋지 않을까요?
Constants 로 정의해서 가져다 쓰게 하는건 어떨까요? 
klaytn도 보면 tx_type 을 정의해서 가져다 쓰게 했거든요~

2020-09-22 03:47 UTC, lix82 commented on index.html
> +          "TransactionType": "AccountSet",
SDK에서 걸러지긴 하는데 .. 추가하겠습니다.

2020-09-22 05:20 UTC, KyungeunKim approved these changes

2020-09-23 06:20 UTC, KyungeunKim approved these changes

2020-09-24 07:59 UTC, merged